# .github/workflows/android-build.yml
name: ðŸ¾ Panther - Android Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Panther

    steps:
    - name: ðŸš€ Checkout PantherDev
      uses: actions/checkout@v4

    - name: â˜• Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: ðŸ˜ Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.5'

    - name: ðŸ—ï¸ Build Debug APK
      run: gradle assembleDebug --stacktrace

    - name: ðŸ“¦ Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: panther-dev-debug-apk
        path: Panther/app/build/outputs/apk/debug/*.apk
        retention-days: 30

    - name: Config APK Signature
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        KEYSTORE_PATH=$RUNNER_TEMP/release.jks
        echo "Ruta de la Keystore: $KEYSTORE_PATH"
        echo "$KEYSTORE_BASE64" | base64 -d > $KEYSTORE_PATH
        echo "KEYSTORE_FILE=$KEYSTORE_PATH" >> $GITHUB_ENV
        echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

    - name: ðŸŽ¯ Build Release APK (signed)
      run: gradle assembleRelease --stacktrace

    - name: ðŸ“¦ Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: panther-dev-release-apk
        path: Panther/app/build/outputs/apk/release/*.apk
        retention-days: 30
